--===========================================================================================
-- [회원 테이블 생성]  *아이디 / 비번 / 이름 / 성별 / 주민등록번호 / 연락처 / 이메일 / 주소 / 은행명 / 대출여부 / 남은 대출한도 / 등록일

--===========================================================================================
CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(20) NOT NULL CONSTRAINT PK_MEMBER_ID PRIMARY KEY,
    MEMBER_PW VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    MEMBER_GENDER VARCHAR2(3) NOT NULL CHECK(MEMBER_GENDER IN('남','여')),
    MEMBER_SSN VARCHAR2(14) NOT NULL,
    MEMBER_PHONE VARCHAR2(13) NOT NULL,
    MEMBER_EMAIL VARCHAR2(30),
    MEMBER_ADDR VARCHAR2(100) NOT NULL,
    MEMBER_BANK VARCHAR2(20) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE
);

COMMENT ON TABLE MEMBER IS '회원정보';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PW IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '이름';
COMMENT ON COLUMN MEMBER.MEMBER_GENDER IS '성별';
COMMENT ON COLUMN MEMBER.MEMBER_SSN IS '주민등록번호';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '연락처';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MEMBER_ADDR IS '주소';
COMMENT ON COLUMN MEMBER.MEMBER_BANK IS '은행명';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입일';




--===========================================================================================
-- [은행 테이블 생성]  *소유자명 / 계좌번호 / 잔액 / 대출여부 / 남은 대출한도 / 등록일
--===========================================================================================
-- SH은행
CREATE TABLE SHBANK(
    SH_ID VARCHAR2(20) NOT NULL CONSTRAINT FK_SH_ID REFERENCES MEMBER(MEMBER_ID),
    SH_NAME VARCHAR2(20) NOT NULL,
    SH_NUM VARCHAR2(14) CONSTRAINT PK_SH_NUM PRIMARY KEY,
    SH_PW VARCHAR2(4) NOT NULL,
    SH_BALANCE NUMBER DEFAULT 0 NOT NULL,
    LOAN_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL CHECK(LOAN_YN IN('Y', 'N')),
    LOAN_MONEY NUMBER DEFAULT 0 NOT NULL,
    LOAN_LIMIT NUMBER DEFAULT 100000000,
    ENROLL_DATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN SHBANK.SH_ID IS '아이디';
COMMENT ON COLUMN SHBANK.SH_NAME IS '이름';
COMMENT ON COLUMN SHBANK.SH_NUM IS '계좌번호';
COMMENT ON COLUMN SHBANK.SH_PW IS '비밀번호';
COMMENT ON COLUMN SHBANK.SH_BALANCE IS '잔액';
COMMENT ON COLUMN SHBANK.LOAN_YN IS '대출가능여부';
COMMENT ON COLUMN SHBANK.LOAN_MONEY IS '대출금액';
COMMENT ON COLUMN SHBANK.LOAN_LIMIT IS '남은대출한도';
COMMENT ON COLUMN SHBANK.ENROLL_DATE IS '등록일';


--KB은행
CREATE TABLE KBBANK(
    KB_ID VARCHAR2(20) NOT NULL CONSTRAINT FK_KB_ID REFERENCES MEMBER(MEMBER_ID),
    KB_NAME VARCHAR2(20) NOT NULL,
    KB_NUM VARCHAR2(14) CONSTRAINT PK_KB_NUM PRIMARY KEY,
    KB_PW VARCHAR2(4) NOT NULL,
    KB_BALANCE NUMBER DEFAULT 0 NOT NULL,
    LOAN_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL CHECK(LOAN_YN IN('Y', 'N')),
    LOAN_MONEY NUMBER DEFAULT 0 NOT NULL,
    LOAN_LIMIT NUMBER DEFAULT 100000000,
    ENROLL_DATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN KBBANK.KB_ID IS '아이디';
COMMENT ON COLUMN KBBANK.KB_NAME IS '이름';
COMMENT ON COLUMN KBBANK.KB_NUM IS '계좌번호';
COMMENT ON COLUMN KBBANK.KB_PW IS '비밀번호';
COMMENT ON COLUMN KBBANK.KB_BALANCE IS '잔액';
COMMENT ON COLUMN KBBANK.LOAN_YN IS '대출가능여부';
COMMENT ON COLUMN KBBANK.LOAN_MONEY IS '대출금액';
COMMENT ON COLUMN KBBANK.LOAN_LIMIT IS '남은대출한도';
COMMENT ON COLUMN KBBANK.ENROLL_DATE IS '등록일';



--===========================================================================================
-- 테스트 데이터 추가
--===========================================================================================
SELECT * FROM MEMBER;
SELECT * FROM SHBANK;
INSERT INTO MEMBER
VALUES('admin', 'admin', '관리자', '남', '960120-1000700', '010-2345-5577', 'admin@bankhi.co.kr', '서울시 마포구 공덕동 12 BANKHi', 'SH은행', DEFAULT);
INSERT INTO SHBANK VALUES('admin', '관리자', '110450573217', '1117', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER
VALUES('kim777', 'kim777', '김일병', '남', '950430-1267444', '010-3111-2433', 'test01@naver.com', '경기도 김포시 북변동 477 3층', 'SH은행', DEFAULT);
INSERT INTO SHBANK VALUES('kim777', '김일병', '110772657355', '1117', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER
VALUES('lee051', 'lee051', '이배구', '남', '910430-1048662', '010-8448-3194', 'ball051@naver.com', '서울시 마포구 공덕동 153-2', 'SH은행', DEFAULT);
INSERT INTO SHBANK VALUES('lee051', '이배구', '110477563905', '2233', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER
VALUES('hwang12', 'hwang12', '황희찬', '남', '960126-1071662', '010-6290-4332', 'soccer11@naver.com', '서울시 강남구 도곡동 777', 'SH은행', DEFAULT);
INSERT INTO SHBANK VALUES('hwang12', '황희찬', '110650321588', '1004', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER
VALUES('yezi27', 'yezi27', '유예지', '여', '930509-2747518', '010-8443-6902', 'dream22@naver.com', '서울시 강남구 논현동 7-99', 'SH은행', DEFAULT);
INSERT INTO SHBANK VALUES('yezi27', '유예지', '117633152044', '2727', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER
VALUES('green', 'green', '이그린', '여', '950430-2051663', '010-2044-6874', 'greeny@naver.com', '서울시 중구 명동 833-5', 'KB은행', DEFAULT);
INSERT INTO KBBANK VALUES('green', '이그린', '1002153787428', '2233', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER
VALUES('kwonss', 'kwonss', '권상우', '남', '811104-1055603', '010-1234-8714', 'kwonss@naver.com', '서울시 강남구 역삼동 6-2', 'KB은행', DEFAULT);
INSERT INTO KBBANK VALUES('kwonss', '권상우', '1005903444215', '0005', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER
VALUES('shotgun', 'shotgun', '오샷건', '남', '750604-1046422', '010-9963-4504', 'shotgun@naver.com', '서울시 중구 회현동 44-5', 'SH은행', DEFAULT);
INSERT INTO SHBANK VALUES('shotgun', '오샷건', '110630715320', '5757', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER
VALUES('minji', 'minji', '김민지', '여', '001204-4071023', '010-6671-2020', 'minji@naver.com', '서울시 강남구 수서동 172', 'KB은행', DEFAULT);
INSERT INTO KBBANK VALUES('minji', '김민지', '1002457854469', '1010', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);


--===========================================================================================
-- 로그 테이블 생성
--===========================================================================================
CREATE TABLE LOG(
    CONTENT VARCHAR2(200),
    TIME DATE
);

COMMIT;